# Generated by Django 5.0.3 on 2024-05-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_question_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
