# Generated by Django 5.0.3 on 2024-05-01 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_bucket_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_buckets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bucket',
        ),
    ]
