# Generated by Django 5.0.3 on 2024-05-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_question_like_users_delete_bucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='like_users',
        ),
    ]
