# Generated by Django 5.0.3 on 2024-05-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_like_like_like_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like',
            field=models.ManyToManyField(to='blog.like'),
        ),
    ]
