# Generated by Django 5.0.3 on 2024-05-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_question_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='like',
            new_name='like_count',
        ),
    ]
