# Generated by Django 5.0.3 on 2024-05-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_question_like_count_question_like_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
