# Generated by Django 5.0.3 on 2024-05-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_question_upload_time_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='hashtag',
            field=models.ManyToManyField(to='community.hashtag'),
        ),
    ]
