# Generated by Django 5.0.3 on 2024-05-07 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_question_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='like',
        ),
        migrations.AddField(
            model_name='question',
            name='like',
            field=models.ManyToManyField(related_name='likeQuestions', to=settings.AUTH_USER_MODEL),
        ),
    ]
