# Generated by Django 5.0.3 on 2024-05-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_question_like_question_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='like',
            new_name='likes',
        ),
    ]
