# Generated by Django 4.2.11 on 2024-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='babopower',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
