# Generated by Django 5.0.5 on 2024-05-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pro_pic',
            field=models.ImageField(default='./static/img/user.png', upload_to=''),
        ),
    ]
