# Generated by Django 5.0.5 on 2024-05-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pro_pic',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
    ]
