# Generated by Django 5.0.3 on 2024-05-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_is_admin_customuser_potatopower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='potatopower',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
