# Generated by Django 4.2.11 on 2024-03-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_question_file_question_subject_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='File'),
        ),
    ]
