# Generated by Django 5.0.3 on 2024-03-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_questiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='questionType',
            field=models.BooleanField(default='코딩 관련 아님', verbose_name='코딩 관련'),
        ),
    ]
