# Generated by Django 5.0.3 on 2024-03-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_post_questiontype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Question',
        ),
    ]
