# Generated by Django 4.2.11 on 2024-04-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_question_upload_time_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='body',
        ),
    ]
