# Generated by Django 4.2.11 on 2024-04-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_rename_content_question_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='body',
            new_name='content',
        ),
    ]
