# Generated by Django 4.2.11 on 2024-03-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_question_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('EDU', '교육, 학문'), ('COM', '컴퓨터통신'), ('GAME', '게임'), ('ART', '엔터테인먼트, 예술'), ('LIFE', '생활'), ('HEALTH', '건강'), ('SOCIAL', '사회, 정치'), ('ECONOMY', '경제'), ('TRAVEL', '여행'), ('SPORT', '스포츠, 레저'), ('SHOPPING', '쇼핑'), ('PLACE', '지역&플레이스'), ('CONCERN', '고민Q&A')], default='uncategorized', max_length=20, verbose_name='Category'),
        ),
    ]
