# Generated by Django 4.2.11 on 2024-03-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_remove_question_subject_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('교육, 학문', '교육, 학문'), ('컴퓨터통신', '컴퓨터통신'), ('게임', '게임'), ('엔터테인먼트, 예술', '엔터테인먼트, 예술'), ('생활', '생활'), ('건강', '건강'), ('사회, 정치', '사회, 정치'), ('경제', '경제'), ('여행', '여행'), ('스포츠, 레저', '스포츠, 레저'), ('쇼핑', '쇼핑'), ('지역&플레이스', '지역&플레이스'), ('고민Q&A', '고민Q&A')], default='uncategorized', max_length=20, verbose_name='Category'),
        ),
    ]
