# Generated by Django 4.2.11 on 2024-04-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_question_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='like',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='like',
            name='title',
        ),
    ]
