# Generated by Django 4.2.11 on 2024-05-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_question_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='like_users',
        ),
    ]
