# Generated by Django 4.2.11 on 2024-04-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_remove_like_contents_remove_like_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
