# Generated by Django 4.2.11 on 2024-04-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_remove_like_like_remove_like_like_count_like_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='likes',
            new_name='like_users',
        ),
    ]
