# Generated by Django 5.0.4 on 2024-05-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_alter_comment_comment_text_alter_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='upload_time',
            field=models.DateTimeField(),
        ),
    ]
