# Generated by Django 5.0.4 on 2024-05-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_alter_question_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='upload_time',
            field=models.DateTimeField(unique=True),
        ),
    ]
