# Generated by Django 5.0.4 on 2024-05-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
