# Generated by Django 5.0.4 on 2024-05-02 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_remove_comment_is_like_remove_question_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='recommend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recommend', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend', to='community.question')),
            ],
        ),
    ]
