# Generated by Django 5.0.4 on 2024-05-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_question_recommend_count_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='좋아요'),
        ),
    ]
