# Generated by Django 5.0.3 on 2024-05-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_question_user_alter_answer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
