# Generated by Django 5.0.4 on 2024-06-27 08:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_user_question_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.RemoveField(
            model_name='question',
            name='body',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('교육, 학문', '교육, 학문'), ('컴퓨터통신', '컴퓨터통신'), ('게임', '게임'), ('엔터테인먼트, 예술', '엔터테인먼트, 예술'), ('생활', '생활'), ('건강', '건강'), ('사회, 정치', '사회, 정치'), ('경제', '경제'), ('여행', '여행'), ('스포츠, 레저', '스포츠, 레저'), ('쇼핑', '쇼핑'), ('지역&플레이스', '지역&플레이스'), ('고민Q&A', '고민Q&A')], default='uncategorized', max_length=20, verbose_name='분야'),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(null=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='사진'),
        ),
        migrations.AddField(
            model_name='question',
            name='like_users',
            field=models.ManyToManyField(related_name='like_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL),
        ),
    ]
